FORMAT: 1A
HOST: http://ampapi.com

# avn
This is a proposed API for Cisco/Avnet AMP app project

## Access [/login]
Methods allowing one to receive a session token
### request session token [POST]

+ Request (application/json)

        {
            "username": "test",
            "password": "password"
        }

+ Response 200 (application/json)

    + Body

            {
                "token": "asda9sf987jhgiouyaisodufy"
            }

+ Response 403 
        
        User / Password pair invalid

## Registration [/register]

### register user [POST]

+ Request (application/json)

        {
            "company":"ACME Inc.",
            "email":"sales@acme.com",
            "firstName":"John",
            "lastName":"Smith",
            "partnerLevel":"GOLD",
            "password":"password",
            "phone":"1234567890",
            "jobFunction":"FIELD_SALES"
        }
        
+ Response 200 (application/json)

            {
                "status": "OK",
                "message": "User registered"
            }

## Quizzes [/quizzes{?token}]

+ Parameters
    + token (String) - security token


## Quiz content [/quizzes/{testId}{?token}]

+ Parameters
    + testId (numeric) - id of the quiz
    + token (String) - security token

### Request content of single quiz [GET]        
        
+ Response 200 (application/json)

        {
          "id": 1,
          "title": "entry level test 1",
          "questions": [
            {
              "id": 0,
              "question": "What is the meaning of life?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": true
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                },
                {
                  "id": 2,
                  "value": "Maybe",
                  "isCorrect": false
                }
              ]
            },
            {
              "id": 1,
              "question": "What is The Answer to the Ultimate Question of Life, The Universe, and Everything?",
              "answers": [
                {
                  "id": 0,
                  "value": "41",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "42",
                  "isCorrect": true
                },
                {
                  "id": 2,
                  "value": "43",
                  "isCorrect": false
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            }
        
          ]
        }
        
+ Response 401

        Token not valid
        
+ Response 404

        Resource not found


## Messages [/messages{?token}]

+ Parameters
    + token (String) - security token

### Request list of message headers [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "title": "OpenDNS is now part of Cisco — Taking Security Everywhere Webcast",
                "published": "2015-09-09T18:25:43.511Z",
                "lead": "We’re excited to share the news that OpenDNS is now part of the Cisco family! The acquisition of OpenDNS builds on Cisco’s “Security Everywhere” vision by adding cloud-delivered network security and global threat intelligence to protect any device, anywhere."
            },
            {
                "id": 2,
                "title": "Cisco Web and Email Security Webinar",
                "published": "2015-08-12T18:25:43.511Z",
                "lead": "Join us for this live webcast on August 18, 2015, at 8 a.m. Pacific Time/11 a.m. Eastern Time."
            },
            {
                "id": 3,
                "title": "Join us for the Winning with VersaStack Webcast Series",
                "published": "2015-07-30T18:25:43.511Z",
                "lead": "Are you looking for a way to engage with your clients; help them optimize their data center operations; and save them substantial money? Are you interested in learning more about an area with strong revenues and rapid growth projections-where IBM and Cisco have established a strong presence in the market? Join us as we present the \"Winning with VersaStack\" webcast series."
            }
        ]

+ Response 401

        Token not valid

+ Response 404

        Resource not found

## Message [/messages/{messageId}{?token}]

+ Parameters
    + token (String) - security token
    + messageId (String) - id of the message

### Request content of single message [GET]
Format of the body will TBD (Base64 encoded HTML?)

+ Response 200 (application/json)

        {
          "id": 1,
          "published": "2015-09-09T18:25:43.511Z",
          "title": "entry level test 1",
          "body": "We’re excited to share the news that OpenDNS is now part of the Cisco family! The acquisition of OpenDNS builds on Cisco’s “Security Everywhere” vision by adding cloud-delivered network security and global threat intelligence to protect any device, anywhere."
        }

+ Response 401

        Token not valid
        
+ Response 404

        Resource not found
        
## Events [/events{?token}]

+ Parameters
    + token (String) - security token

### Request list of events [GET]

+ Response 200 (application/json)

        [
          {
            "id":1,
            "dateStart": "2016-01-05T18:00:00.000Z",
            "dateEnd": "2016-01-06T01:00:00.000Z",
            "name": "Cisco ASA Express Seminar - Dallas, TX",
            "description": "his seminar reviews the concepts and technologies covered and included in the Cisco ASA Express Security (SAEXS) #500-260 exam. Seminar hours are 9:00am to 4:30pm each day",
            "place": "Avnet 2021 Lakeside Blvd Richardson, TX",
            "lineUp": "Day 1: Cisco ASA NGFW Solution Introduction - Cisco ASA with FirePOWER Policies Malware/File IPS (Snort) Access Control Network Discovery (FireSIGHT) Correlation Day 2: FirePower Continued and ASA Features ASA FirePOWER Services: Positioning and best practices ASA VPN features, positioning and best practices ASA Licensing ASA Cloud Web Security",
            "category": "WEBINARS"
          },
          {
            "id":2,
            "dateStart": "2016-01-05T18:00:00.000Z",
            "dateEnd": "2016-01-06T01:00:00.000Z",
            "name": "Cisco ASA Express Seminar - Dallas, TX",
            "description": "his seminar reviews the concepts and technologies covered and included in the Cisco ASA Express Security (SAEXS) #500-260 exam. Seminar hours are 9:00am to 4:30pm each day",
            "place": "Avnet 2021 Lakeside Blvd Richardson, TX",
            "lineUp": "Day 1: Cisco ASA NGFW Solution Introduction - Cisco ASA with FirePOWER Policies Malware/File IPS (Snort) Access Control Network Discovery (FireSIGHT) Correlation Day 2: FirePower Continued and ASA Features ASA FirePOWER Services: Positioning and best practices ASA VPN features, positioning and best practices ASA Licensing ASA Cloud Web Security",
            "category": "CLOUD"
          }
        ]

+ Response 401

        Token not valid
       
       
## Event details [/events/{id}{?token}]

+ Parameters
    + token (String) - security token
    + id (String) - id of event

### Request single event [GET]

+ Response 200 (application/json)

        {
            "id":1,
            "dateStart": "2016-01-05T18:00:00.000Z",
            "dateEnd": "2016-01-06T01:00:00.000Z",
            "name": "Cisco ASA Express Seminar - Dallas, TX",
            "description": "his seminar reviews the concepts and technologies covered and included in the Cisco ASA Express Security (SAEXS) #500-260 exam. Seminar hours are 9:00am to 4:30pm each day",
            "place": "Avnet 2021 Lakeside Blvd Richardson, TX",
            "lineUp": "Day 1: Cisco ASA NGFW Solution Introduction - Cisco ASA with FirePOWER Policies Malware/File IPS (Snort) Access Control Network Discovery (FireSIGHT) Correlation Day 2: FirePower Continued and ASA Features ASA FirePOWER Services: Positioning and best practices ASA VPN features, positioning and best practices ASA Licensing ASA Cloud Web Security",
            "category": "WEBINARS"
        }
        
+ Response 403
        
        Token not valid
        
+ Response 404

        Resource not found
       

## Own profile [/users/me/profile{?token}]

+ Parameters
    + token (String) - security token

### Update own profile [PUT]

+ Request (application/json)

        {
          "accountManagerId": 0,
          "certificates": {
            "ciscoNotsure": true,
            "cse": false,
            "dca": false,
            "dcucam": true,
            "dcucd": false,
            "dcuci": true,
            "dcuct": false,
            "dcuft": false,
            "emcNotsure": false,
            "emcapd": false,
            "emcca": true,
            "emcdca": false,
            "emcds": true,
            "emcie": false,
            "emcpe": false,
            "emcsa": false,
            "emcsya": true,
            "emcta": false,
            "hdsca": true,
            "hdsci": false,
            "hdscp": true,
            "hdscsm": false,
            "hdscss": false,
            "hdssq": false,
            "hdsstc": false,
            "hitachiNotsure": false,
            "naip": false,
            "nasa": false,
            "nasap": false,
            "nasep": false,
            "nasp": false,
            "nasvp": false,
            "natsp": false,
            "navdip": false,
            "ncda": false,
            "ncie": false,
            "netAppNotsure": false,
            "netappase": false
          },
          "interests": {
            "asigra": false,
            "backupAndRecovery": false,
            "bussinessApplications": true,
            "ciscoPortfolio": false,
            "ciscoServices": false,
            "cloud": false,
            "convergedInfrastructure": false,
            "dataCenter": false,
            "flexpodDatacenter": false,
            "flexpodExpress": false,
            "flexpodSap": true,
            "flexpodSelect": false,
            "hitachiUcp": false,
            "managedServices": false,
            "networking": true,
            "numberOfLocations": 5,
            "otherInterests": "some text",
            "otherTrainigs": "",
            "security": false,
            "serversComputing": false,
            "storaServerSolution": false,
            "storage": true,
            "vBlock": true,
            "virtualization": false,
            "vspex": false
          },
          "other": {
            "dell": true,
            "facebook": true,
            "googlePlus": true,
            "hp": false,
            "ibm": false,
            "linkedIn": true,
            "otherVendors": true,
            "twitter": false,
            "youTube": true
          },
          "company": "ACME",
          "email": "john.s@acme.com",
          "firstName": "John",
          "lastName": "Smith",
          "partnerLevel": "REGISTERED",
          "phone": "123456789",
          "workingFunction": "FIELD_SALES"
        }

+ Response 200

        {
            "message": "Operation successful",
            "status": 200
        }
        
+ Response 401
        
        Token not valid

### Get own profile [GET]

+ Response 200 (application/json)

        {
          "accountManagerId": 0,
          "certificates": {
            "ciscoNotsure": true,
            "cse": false,
            "dca": false,
            "dcucam": true,
            "dcucd": false,
            "dcuci": true,
            "dcuct": false,
            "dcuft": false,
            "emcNotsure": false,
            "emcapd": false,
            "emcca": true,
            "emcdca": false,
            "emcds": true,
            "emcie": false,
            "emcpe": false,
            "emcsa": false,
            "emcsya": true,
            "emcta": false,
            "hdsca": true,
            "hdsci": false,
            "hdscp": true,
            "hdscsm": false,
            "hdscss": false,
            "hdssq": false,
            "hdsstc": false,
            "hitachiNotsure": false,
            "naip": false,
            "nasa": false,
            "nasap": false,
            "nasep": false,
            "nasp": false,
            "nasvp": false,
            "natsp": false,
            "navdip": false,
            "ncda": false,
            "ncie": false,
            "netAppNotsure": false,
            "netappase": false
          },
          "interests": {
            "asigra": false,
            "backupAndRecovery": false,
            "bussinessApplications": true,
            "ciscoPortfolio": false,
            "ciscoServices": false,
            "cloud": false,
            "convergedInfrastructure": false,
            "dataCenter": false,
            "flexpodDatacenter": false,
            "flexpodExpress": false,
            "flexpodSap": true,
            "flexpodSelect": false,
            "hitachiUcp": false,
            "managedServices": false,
            "networking": true,
            "numberOfLocations": 5,
            "otherInterests": "some text",
            "otherTrainigs": "",
            "security": false,
            "serversComputing": false,
            "storaServerSolution": false,
            "storage": true,
            "vBlock": true,
            "virtualization": false,
            "vspex": false
          },
          "other": {
            "dell": true,
            "facebook": true,
            "googlePlus": true,
            "hp": false,
            "ibm": false,
            "linkedIn": true,
            "otherVendors": true,
            "twitter": false,
            "youTube": true
          },
          "company": "ACME",
          "email": "john.s@acme.com",
          "firstName": "John",
          "lastName": "Smith",
          "partnerLevel": "REGISTERED",
          "phone": "123456789",
          "workingFunction": "FIELD_SALES"
        }

+ Response 401
        
        Token not valid

## Resources [/resources{?resourceType}{?token}]

+ Parameters
    + resourceType (optional, String) - type of resource document|video|link
    + token (String) - security token

### Request list of Resources [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "NETAPP FLEXPOD EXPRESS VIDEO",
                "type": 1,
                "url": "https://www.youtube.com/watch?v=6RblcQLXwHw",
                "category": "Non"
            },
            {
                "id": 2,
                "name": "Tralalala Video ya!",
                "type": 1,
                "url": "https://www.youtube.com/watch?v=aKTWpcRGcjA",
                "category": "Non"
            },
            {
                "id": 3,
                "name": "Video",
                "type": 1,
                "url": "https://www.youtube.com/watch?v=oMUDyvhSkf4",
                "category": "Non"
            },
            {
                "id": 4,
                "name": "Tralalala document ya!",
                "type": 0,
                "url": "https://www.youtube.com/watch?v=aKTWpcRGcjA",
                "category": "critical"
            },
            {
                "id": 5,
                "name": "document",
                "type": 0,
                "url": "http://www.avnetamp.com/flow/show_media/355",
                "category": "critical"
            },
            {
                "id": 6,
                "name": "Tralalala document ya!",
                "type": 0,
                "url": "http://www.avnetamp.com/flow/show_media/356",
                "category": "critical"
            },
            {
                "id": 7,
                "name": "Tralalala document ya!",
                "type": 0,
                "url": "http://www.avnetamp.com/flow/show_media/357",
                "category": "critical"
            },
            {
                "id": 8,
                "name": "Tralalala document ya!",
                "type": 0,
                "url": "http://www.avnetamp.com/flow/show_media/358",
                "category": "critical"
            },
            {
                "id": 9,
                "name": "Tralalala document ya!",
                "type": 0,
                "url": "http://www.avnetamp.com/flow/show_media/359",
                "category": "additional"
            },
            {
                "id": 10,
                "name": "Tralalala document ya!",
                "type": 0,
                "url": "http://www.avnetamp.com/flow/show_media/360",
                "category": "additional"
            },
            {
                "id": 11,
                "name": "Tralalala document ya!",
                "type": 0,
                "url": "http://www.avnetamp.com/flow/show_media/361",
                "category": "additional"
            }
        ]
        

+ Response 401

        Token not valid

## Enablement tracks [/tracks{?token}]

+ Parameters
    + token (String) - security token

### Request tracks content for current user [GET]

+ Response 200 (application/json)

        [
          {
            "id": 0,
            "name": "Category A",
            "permissionGranted": false,
            "tracks": [
              {
                "additionalDocuments": [
                  {
                    "category": "SECURITY",
                    "id": 0,
                    "name": "Test pptx",
                    "type": 0,
                    "url": "https://oit.utk.edu/instructional/strategies/toolkit/Anonymous%20Assets/sample%20PowerPoint%20presentation.pptx"
                  }
                ],
                "alreadyPassed": false,
                "attemptsLast": 0,
                "criticalDocuments": [
                  {
                    "category": "SECURITY",
                    "id": 1,
                    "name": "test pdf",
                    "type": 0,
                    "url": "http://kmmc.in/wp-content/uploads/2014/01/lesson2.pdf"
                  }
                ],
                "previousAttempts": 0,
                "quizId": 0,
                "trackId": 0,
                "trackName": "Track a1",
                "videos": [
                  {
                    "category": "SECURITY",
                    "id": 2,
                    "name": "Video",
                    "type": 0,
                    "url": "https://www.youtube.com/watch?v\u003dKzV_UCQFY6w"
                  }
                ]
              },
              {
                "alreadyPassed": false,
                "attemptsLast": 0,
                "previousAttempts": 0,
                "quizId": 0,
                "trackId": 0,
                "trackName": "Track a2"
              },
              {
                "alreadyPassed": false,
                "attemptsLast": 0,
                "previousAttempts": 0,
                "quizId": 0,
                "trackId": 0,
                "trackName": "Track a3"
              }
            ]
          },
          {
            "id": 0,
            "name": "Category B",
            "permissionGranted": false,
            "tracks": [
              {
                "alreadyPassed": false,
                "attemptsLast": 0,
                "previousAttempts": 0,
                "quizId": 0,
                "trackId": 0,
                "trackName": "track b1"
              },
              {
                "alreadyPassed": false,
                "attemptsLast": 0,
                "previousAttempts": 0,
                "quizId": 0,
                "trackId": 0,
                "trackName": "track b2"
              },
              {
                "alreadyPassed": false,
                "attemptsLast": 0,
                "previousAttempts": 0,
                "quizId": 0,
                "trackId": 0,
                "trackName": "track b3"
              }
            ]
          }
        ]

+ Response 401

        Wrong token