FORMAT: 1A

# avn
This is a proposed API for Cisco/Avnet AMP app project

## Access [/login]
Methods allowing one to receive a session token
### request session token [POST]

+ Request (application/json)

        {
            "username": "test",
            "password": "password"
        }

+ Response 200 (application/json)

    + Body

            {
                "token": "asda9sf987jhgiouyaisodufy"
            }

+ Response 403 
        
        User / Password pair invalid


## Registration [/register]

### register user [POST]

+ Request (application/json)

        {
            "company":"ACME Inc.",
            "email":"sales@acme.com",
            "firstName":"John",
            "lastName":"Smith",
            "partnerLevel":"GOLD",
            "password":"password",
            "phone":"1234567890",
            "workingFunction":"FIELD_SALES"
        }
        
+ Response 200 (application/json)

            {
                "status": "OK",
                "message": "User registered"
            }

## Quizzes [/quizzes{?token}]

+ Parameters
    + token (String) - security token

### Request list of quizzes [GET]

+ Response 200 (application/json)

        [
          {
            "title":"entry level test 1",
            "id":1
          },
          {
            "title":"Quiz for a more advanced user",
            "id":2
          },
          {
            "title":"test 3",
            "id":3
          },
          {
            "title":"test 4",
            "id":4
          },
          {
            "title":"test 5",
            "id":5
          },
          {
            "title":"test 6",
            "id":6
          },
          {
            "title":"test 7",
            "id":7
          },
          {
            "title":"test 8",
            "id":8
          },
          {
            "title":"test 9",
            "id":9
          },
          {
            "title":"test 10",
            "id":10
          }
        ]
        
+ Response 401

        Token not valid

## Quiz content [/quizzes/{testId}{?token}]

+ Parameters
    + testId (numeric) - id of the quiz
    + token (String) - security token

### Request content of single quiz [GET]        
        
+ Response 200 (application/json)

        {
          "id": 1,
          "title": "entry level test 1",
          "questions": [
            {
              "id": 0,
              "question": "What is the meaning of life?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": true
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                },
                {
                  "id": 2,
                  "value": "Maybe",
                  "isCorrect": false
                }
              ]
            },
            {
              "id": 1,
              "question": "What is The Answer to the Ultimate Question of Life, The Universe, and Everything?",
              "answers": [
                {
                  "id": 0,
                  "value": "41",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "42",
                  "isCorrect": true
                },
                {
                  "id": 2,
                  "value": "43",
                  "isCorrect": false
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            },
            {
              "id": 1,
              "question": "Will the first order win?",
              "answers": [
                {
                  "id": 0,
                  "value": "Yes",
                  "isCorrect": false
                },
                {
                  "id": 1,
                  "value": "No",
                  "isCorrect": true
                }
              ]
            }
        
          ]
        }
        
+ Response 401

        Token not valid


## Messages [/messages{?token}]

+ Parameters
    + token (String) - security token

### Request list of message headers [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "title": "OpenDNS is now part of Cisco — Taking Security Everywhere Webcast",
                "published": "2015-09-09T18:25:43.511Z",
                "lead": "We’re excited to share the news that OpenDNS is now part of the Cisco family! The acquisition of OpenDNS builds on Cisco’s “Security Everywhere” vision by adding cloud-delivered network security and global threat intelligence to protect any device, anywhere."
            },
            {
                "id": 2,
                "title": "Cisco Web and Email Security Webinar",
                "published": "2015-08-12T18:25:43.511Z",
                "lead": "Join us for this live webcast on August 18, 2015, at 8 a.m. Pacific Time/11 a.m. Eastern Time."
            },
            {
                "id": 3,
                "title": "Join us for the Winning with VersaStack Webcast Series",
                "published": "2015-07-30T18:25:43.511Z",
                "lead": "Are you looking for a way to engage with your clients; help them optimize their data center operations; and save them substantial money? Are you interested in learning more about an area with strong revenues and rapid growth projections-where IBM and Cisco have established a strong presence in the market? Join us as we present the \"Winning with VersaStack\" webcast series."
            }
        ]

+ Response 401

        Token not valid

## Message [/messages/{messageId}{?token}]

+ Parameters
    + token (String) - security token

### Request content of single message [GET]
Format of the body will TBD (Base64 encoded HTML?)

+ Response 200 (application/json)

        {
          "id": 1,
          "published": "2015-09-09T18:25:43.511Z",
          "title": "entry level test 1",
          "body": "We’re excited to share the news that OpenDNS is now part of the Cisco family! The acquisition of OpenDNS builds on Cisco’s “Security Everywhere” vision by adding cloud-delivered network security and global threat intelligence to protect any device, anywhere."
        }

+ Response 401

        Token not valid
        
## Events [/events{?token}]

+ Parameters
    + token (String) - security token

### Request list of events [GET]

+ Response 200 (application/json)

        [
          {
            "dateStart": "2016-01-05T18:00:00.000Z",
            "dateEnd": "2016-01-06T01:00:00.000Z",
            "name": "Cisco ASA Express Seminar - Dallas, TX",
            "description": "his seminar reviews the concepts and technologies covered and included in the Cisco ASA Express Security (SAEXS) #500-260 exam. Seminar hours are 9:00am to 4:30pm each day",
            "place": "Avnet 2021 Lakeside Blvd Richardson, TX",
            "lineUp": "Day 1: Cisco ASA NGFW Solution Introduction - Cisco ASA with FirePOWER Policies Malware/File IPS (Snort) Access Control Network Discovery (FireSIGHT) Correlation Day 2: FirePower Continued and ASA Features ASA FirePOWER Services: Positioning and best practices ASA VPN features, positioning and best practices ASA Licensing ASA Cloud Web Security",
            "category": "WEBINARS"
          },
          {
            "dateStart": "2016-01-05T18:00:00.000Z",
            "dateEnd": "2016-01-06T01:00:00.000Z",
            "name": "Cisco ASA Express Seminar - Dallas, TX",
            "description": "his seminar reviews the concepts and technologies covered and included in the Cisco ASA Express Security (SAEXS) #500-260 exam. Seminar hours are 9:00am to 4:30pm each day",
            "place": "Avnet 2021 Lakeside Blvd Richardson, TX",
            "lineUp": "Day 1: Cisco ASA NGFW Solution Introduction - Cisco ASA with FirePOWER Policies Malware/File IPS (Snort) Access Control Network Discovery (FireSIGHT) Correlation Day 2: FirePower Continued and ASA Features ASA FirePOWER Services: Positioning and best practices ASA VPN features, positioning and best practices ASA Licensing ASA Cloud Web Security",
            "category": "CLOUD"
          }
        ]

+ Response 401

        Token not valid
       
## Articles [/articles{?token}]

+ Parameters
    + token (String) - security token

### Request list of articles [GET]

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "title": "AVNET'S DRIVING SOLUTIONS WEBINAR SERIES",
            "header": "Avnet’s Driving Solutions webinar series continues with The Internet of Everything and the Impact on Enterprise Applications. Because I know you’re not busy yet, join us on Thursday, October 16th at 10:00 AM PST.",
            "iconUrl": "http://www.avnetamp.com/media/updated/Articles-BIGimg_060814.png",
            "category": "EVENTS"
          },
          {
            "id": 1,
            "title": "CISCO+NETAPP = FLEXPOD AT CISCO LIVE",
            "header": "There I was, just sitting at my cube pondering, “What’s the #1 ranked integrated infrastructure solution from Cisco and NetApp?” when a coworker walked by and told me about the FlexPod that ran Cisco Live.",
            "iconUrl": "http://www.avnetamp.com/media/updated/Articles-BIGimg_060214.png",
            "category": "EVENTS"
          }
        ]

+ Response 444

        Token not valid

## Videos [/resources/videos{?token}]

Available videos

+ Parameters
    + token (String) - security token

### Request list of videos [GET]

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "title": "NETAPP FLEXPOD EXPRESS VIDEO",
            "header": "This time lapse video highlight's Avnet's FlexPod integration services.",
            "iconUrl": "http://www.avnetamp.com/media/updated/Articles-BIGimg_060814.png",
            "videoUrl": "https://www.youtube.com/watch?v=ewUTqW5ntqM",
            "category": "SECURITY"
          },
          {
            "id": 1,
            "title": "Cisco FlexPod Express Video",
            "header": "This time lapse video highlight's Avnet's FlexPod integration services.",
            "iconUrl": "http://www.avnetamp.com/media/updated/Articles-BIGimg_060814.png",
            "videoUrl": "https://www.youtube.com/watch?v=DJponlkm1PA",
            "category": "SECURITY"
          }
        ]
        
+ Response 401

        Token not valid
        
## Own profile [/users/me/profile{?token}]

+ Parameters
    + token (String) - security token

### Update own profile [PUT]

+ Request (application/json)

        {
          "accountManagerId": 0,
          "certificates": {
            "ciscoNotsure": true,
            "cse": false,
            "dca": false,
            "dcucam": true,
            "dcucd": false,
            "dcuci": true,
            "dcuct": false,
            "dcuft": false,
            "emcNotsure": false,
            "emcapd": false,
            "emcca": true,
            "emcdca": false,
            "emcds": true,
            "emcie": false,
            "emcpe": false,
            "emcsa": false,
            "emcsya": true,
            "emcta": false,
            "hdsca": true,
            "hdsci": false,
            "hdscp": true,
            "hdscsm": false,
            "hdscss": false,
            "hdssq": false,
            "hdsstc": false,
            "hitachiNotsure": false,
            "naip": false,
            "nasa": false,
            "nasap": false,
            "nasep": false,
            "nasp": false,
            "nasvp": false,
            "natsp": false,
            "navdip": false,
            "ncda": false,
            "ncie": false,
            "netAppNotsure": false,
            "netappase": false
          },
          "interests": {
            "asigra": false,
            "backupAndRecovery": false,
            "bussinessApplications": true,
            "ciscoPortfolio": false,
            "ciscoServices": false,
            "cloud": false,
            "convergedInfrastructure": false,
            "dataCenter": false,
            "flexpodDatacenter": false,
            "flexpodExpress": false,
            "flexpodSap": true,
            "flexpodSelect": false,
            "hitachiUcp": false,
            "managedServices": false,
            "networking": true,
            "numberOfLocations": 5,
            "otherInterests": "some text",
            "otherTrainigs": "",
            "security": false,
            "serversComputing": false,
            "storaServerSolution": false,
            "storage": true,
            "vBlock": true,
            "virtualization": false,
            "vspex": false
          },
          "other": {
            "dell": true,
            "facebook": true,
            "googlePlus": true,
            "hp": false,
            "ibm": false,
            "linkedIn": true,
            "otherVendors": true,
            "twitter": false,
            "youTube": true
          },
          "company": "ACME",
          "email": "john.s@acme.com",
          "firstName": "John",
          "lastName": "Smith",
          "partnerLevel": "REGISTERED",
          "phone": "123456789",
          "workingFunction": "FIELD_SALES"
        }

+ Response 200

        {
            "message": "Operation successful",
            "status": 200
        }
        
+ Response 401
        
        Token not valid

### Get own profile [GET]

+ Response 200 (application/json)

        {
          "accountManagerId": 0,
          "certificates": {
            "ciscoNotsure": true,
            "cse": false,
            "dca": false,
            "dcucam": true,
            "dcucd": false,
            "dcuci": true,
            "dcuct": false,
            "dcuft": false,
            "emcNotsure": false,
            "emcapd": false,
            "emcca": true,
            "emcdca": false,
            "emcds": true,
            "emcie": false,
            "emcpe": false,
            "emcsa": false,
            "emcsya": true,
            "emcta": false,
            "hdsca": true,
            "hdsci": false,
            "hdscp": true,
            "hdscsm": false,
            "hdscss": false,
            "hdssq": false,
            "hdsstc": false,
            "hitachiNotsure": false,
            "naip": false,
            "nasa": false,
            "nasap": false,
            "nasep": false,
            "nasp": false,
            "nasvp": false,
            "natsp": false,
            "navdip": false,
            "ncda": false,
            "ncie": false,
            "netAppNotsure": false,
            "netappase": false
          },
          "interests": {
            "asigra": false,
            "backupAndRecovery": false,
            "bussinessApplications": true,
            "ciscoPortfolio": false,
            "ciscoServices": false,
            "cloud": false,
            "convergedInfrastructure": false,
            "dataCenter": false,
            "flexpodDatacenter": false,
            "flexpodExpress": false,
            "flexpodSap": true,
            "flexpodSelect": false,
            "hitachiUcp": false,
            "managedServices": false,
            "networking": true,
            "numberOfLocations": 5,
            "otherInterests": "some text",
            "otherTrainigs": "",
            "security": false,
            "serversComputing": false,
            "storaServerSolution": false,
            "storage": true,
            "vBlock": true,
            "virtualization": false,
            "vspex": false
          },
          "other": {
            "dell": true,
            "facebook": true,
            "googlePlus": true,
            "hp": false,
            "ibm": false,
            "linkedIn": true,
            "otherVendors": true,
            "twitter": false,
            "youTube": true
          },
          "company": "ACME",
          "email": "john.s@acme.com",
          "firstName": "John",
          "lastName": "Smith",
          "partnerLevel": "REGISTERED",
          "phone": "123456789",
          "workingFunction": "FIELD_SALES"
        }

+ Response 401
        
        Token not valid
